version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: 
    working_directory: ~/circleci-demo-java-spring
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: web-{{ checksum "pom.xml" }}
      
      - run: | 
            cd web
            mvn dependency:go-offline 
            cd ../listener
            mvn dependency:go-offline 
            cd ..
      
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: web-{{ checksum "pom.xml" }}
      
      - run: |
           cd web
           mvn package 
           cd ../listener
           mvn package
           cd ..

#      - setup_remote_docker:
#          docker_layer_caching: true 

#      - run: |
#          TAG=1.0.$CIRCLE_BUILD_NUM
#          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
#          cd web/docker
#          ./build $TAG
#          cd ../../listener/docker
#          ./build $TAG
  
      